# Import modules

In [198]:
import numpy as np
import pandas as pd
from src.data_cleaning import perform_data_cleaning
from sklearn.experimental import enable_iterative_imputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split
from pathlib import Path
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator, IterativeImputer
from sklearn.model_selection import cross_validate
from sklearn.metrics import mean_absolute_error, r2_score
from IPython.display import display

In [180]:
from sklearn import set_config

set_config(transform_output="pandas")

# Load the Data

In [181]:
path = Path("..")/"data"/"raw"/"swiggy.csv"
raw_data = pd.read_csv(path)
raw_data.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

# Clean Data

In [182]:
final_df = perform_data_cleaning(raw_data)
final_df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149,short
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,BANG,25,3,friday,0,5.0,19.0,evening,20.183530,very_long
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758,short
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401,medium
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138,medium

In [183]:
pd.Series(final_df.columns,name="columns")

0                 rider_id
1                      age
2                  ratings
3      restaurant_latitude
4     restaurant_longitude
5        delivery_latitude
6       delivery_longitude
7               order_date
8                  weather
9                  traffic
10       vehicle_condition
11           type_of_order
12         type_of_vehicle
13     multiple_deliveries
14                festival
15               city_type
16              time_taken
17               city_name
18               order_day
19             order_month
20       order_day_of_week
21              is_weekend
22     pickup_time_minutes
23         order_time_hour
24       order_time_of_day
25                distance
26           distance_type
Name: columns, dtype: object

In [184]:
# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "order_day_of_week",
                    "city_name"]

final_df.drop(columns=columns_to_drop, inplace=True)
final_df.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,order_month,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,3,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,3,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,3,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,4,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,3,1,15.0,afternoon,6.210138,medium

In [185]:
# check for missing values

final_df.isna().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
type_of_order             0
type_of_vehicle           0
multiple_deliveries     993
festival                228
city_type              1198
time_taken                0
order_month               0
is_weekend                0
pickup_time_minutes    1640
order_time_of_day      2070
distance               3630
distance_type          3630
dtype: int64

In [186]:
# check for duplicates

final_df.duplicated().sum()

np.int64(0)

# experiment initial setup

In [187]:
import mlflow
import mlflow.sklearn
import os
from dotenv import load_dotenv
load_dotenv()
DAGSHUB_USERNAME = os.getenv("DAGSHUB_USERNAME")
DAGSHUB_PASSWORD = os.getenv("DAGSHUB_PASSWORD")
url = f"https://{DAGSHUB_USERNAME}:{DAGSHUB_PASSWORD}@dagshub.com/spynom/my-first-repo.mlflow"

In [188]:
# mlflow server setup
mlflow.set_tracking_uri(url)

In [189]:
# mlflow experiment

mlflow.set_experiment("Exp 1 - Keep Vs Drop Missing Values")

<Experiment: artifact_location='mlflow-artifacts:/6c3ec10558c74619afb82efdacf750d7', creation_time=1743846063260, experiment_id='2', last_update_time=1743846063260, lifecycle_stage='active', name='Exp 1 - Keep Vs Drop Missing Values', tags={}>

In [190]:
# do basic preprocessing

num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather','type_of_order',
                    'type_of_vehicle',"festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [191]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

# Experiment

### run 1 - dropping missing values

In [192]:
def drop_null_run(df:pd.DataFrame):
    with mlflow.start_run():
            mlflow.set_tag("mlflow.runName", f"Drop Null Method")
            mlflow.set_tag("experiment_type", "drop null values")
            mlflow.log_param("mlflow.runName",f"Drop Null Method")
            df =df.dropna(how="any").reset_index(drop=True).copy()


            # build a preprocessor

            preprocessor = ColumnTransformer(transformers=[
                ("scale", MinMaxScaler(), num_cols),
                ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",sparse_output=False), nominal_cat_cols),
                ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order]), ordinal_cat_cols)
            ],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

            preprocessor.set_output(transform="pandas")



            X = df.drop(columns='time_taken')
            y = df['time_taken']

            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

            # transform target column

            pt = PowerTransformer()
            pt.fit(y_train.values.reshape(-1,1))

            # model
            rf = RandomForestRegressor()

            model = TransformedTargetRegressor(
            regressor=rf,
            func=pt.transform,
            inverse_func=pt.inverse_transform
            )

            pipe = Pipeline(
            [

                ("preprocessor", preprocessor),
                ("model", model),
            ]
            )

            cv_results = cross_validate(pipe,X_train,y_train,cv=5,return_train_score=True)

            # Extract test scores
            test_scores = cv_results["test_score"]

            mlflow.log_metric("cv_test_scores",np.mean(test_scores))
            mlflow.log_metric("cv_test_negative_std_scores",-1*np.std(test_scores))

            pipe.fit(X_train, y_train)

            mlflow.log_params(pipe.get_params())


            train_y_pred = pipe.predict(X_train)
            test_y_pred = pipe.predict(X_test)

            mlflow.log_metric("negative_train_MAE",-1*mean_absolute_error(y_train,train_y_pred))
            mlflow.log_metric("negative_test_MAE",-1*mean_absolute_error(y_test,test_y_pred))
            mlflow.log_metric("train_r2_score",r2_score(y_train,train_y_pred))
            mlflow.log_metric("test_r2_score",r2_score(y_test,test_y_pred))

In [193]:
drop_null_run(final_df)

🏃 View run Drop Null Method at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2/runs/822b9c347f974976a89be4524ec3364e
🧪 View experiment at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2

###  Run 2 - filling with central tendency

In [194]:
def fillna_with_central_value(df:pd.DataFrame):
    with mlflow.start_run():
            mlflow.set_tag("mlflow.runName", f"Center Value fill Method")
            mlflow.set_tag("experiment_type", "fill null values")
            mlflow.log_param("mlflow.runName",f"Center Value fill Method")
            df =df.dropna(how="any").reset_index(drop=True).copy()


            # build a preprocessor

            preprocessor = ColumnTransformer(transformers=[

                ("num_cols_pipe", Pipeline(
                 [   ("scaling",MinMaxScaler()),
                     ("imputer", SimpleImputer(strategy="mean")),
                ]
                ), num_cols),
                ("nominal_cols_pipe", Pipeline([
                    ("one_hot_encoding",OneHotEncoder(drop="first",handle_unknown="ignore",sparse_output=False)),
                    ("imputer", SimpleImputer(strategy="most_frequent"))
                    ]), nominal_cat_cols),
                ("ordinal_cols_pipe",Pipeline([
                    ("ordinal_encode",OrdinalEncoder(categories=[traffic_order,distance_type_order])),
                    ("imputer", SimpleImputer(strategy="most_frequent"))
                    ]),ordinal_cat_cols)
            ],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

            preprocessor.set_output(transform="pandas")



            X = df.drop(columns='time_taken')
            y = df['time_taken']

            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

            # transform target column

            pt = PowerTransformer()
            pt.fit(y_train.values.reshape(-1,1))

            # model
            rf = RandomForestRegressor()

            model = TransformedTargetRegressor(
            regressor=rf,
            func=pt.transform,
            inverse_func=pt.inverse_transform
            )

            pipe = Pipeline(
            [

                ("preprocessor", preprocessor),
                ("model", model),
            ]
            )

            cv_results = cross_validate(pipe,X_train,y_train,cv=5,return_train_score=True)

            # Extract test scores
            test_scores = cv_results["test_score"]

            mlflow.log_metric("cv_test_scores",np.mean(test_scores))
            mlflow.log_metric("cv_test_negative_std_scores",-1*np.std(test_scores))

            pipe.fit(X_train, y_train)

            mlflow.log_params(pipe.get_params())


            train_y_pred = pipe.predict(X_train)
            test_y_pred = pipe.predict(X_test)

            mlflow.log_metric("negative_train_MAE",-1*mean_absolute_error(y_train,train_y_pred))
            mlflow.log_metric("negative_test_MAE",-1*mean_absolute_error(y_test,test_y_pred))
            mlflow.log_metric("train_r2_score",r2_score(y_train,train_y_pred))
            mlflow.log_metric("test_r2_score",r2_score(y_test,test_y_pred))

In [195]:
fillna_with_central_value(final_df)

🏃 View run Center Value fill Method at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2/runs/f98427273bd149eba5f6b268354a6c81
🧪 View experiment at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2

### run 3 - knn Imputer

In [196]:
def knn_imputer_run(df:pd.DataFrame):
    with mlflow.start_run():
            mlflow.set_tag("mlflow.runName", f"KNN Imputer Method")
            mlflow.set_tag("experiment_type", "fill null values")
            mlflow.log_param("mlflow.runName",f"KNN Imputer Method")
            df =df.dropna(how="any").reset_index(drop=True).copy()


            # build a preprocessor

            preprocessor = ColumnTransformer(transformers=[
                ("scale", MinMaxScaler(), num_cols),
                ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",sparse_output=False), nominal_cat_cols),
                ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order]), ordinal_cat_cols)
            ],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

            preprocessor.set_output(transform="pandas")



            X = df.drop(columns='time_taken')
            y = df['time_taken']

            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

            # transform target column

            pt = PowerTransformer()
            pt.fit(y_train.values.reshape(-1,1))

            # model
            rf = RandomForestRegressor()

            model = TransformedTargetRegressor(
            regressor=rf,
            func=pt.transform,
            inverse_func=pt.inverse_transform
            )

            pipe = Pipeline(
            [

                ("preprocessor", preprocessor),
                ("knn imputer",KNNImputer(n_neighbors=5,weights="distance")),
                ("model", model),
            ]
            )

            cv_results = cross_validate(pipe,X_train,y_train,cv=5,return_train_score=True)

            # Extract test scores
            test_scores = cv_results["test_score"]

            mlflow.log_metric("cv_test_scores",np.mean(test_scores))
            mlflow.log_metric("cv_test_negative_std_scores",-1*np.std(test_scores))

            pipe.fit(X_train, y_train)

            mlflow.log_params(pipe.get_params())


            train_y_pred = pipe.predict(X_train)
            test_y_pred = pipe.predict(X_test)

            mlflow.log_metric("negative_train_MAE",-1*mean_absolute_error(y_train,train_y_pred))
            mlflow.log_metric("negative_test_MAE",-1*mean_absolute_error(y_test,test_y_pred))
            mlflow.log_metric("train_r2_score",r2_score(y_train,train_y_pred))
            mlflow.log_metric("test_r2_score",r2_score(y_test,test_y_pred))

In [197]:
knn_imputer_run(final_df)

🏃 View run KNN Imputer Method at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2/runs/fcc7ad5ee29d4189862a900ec304e855
🧪 View experiment at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2

### run 4 - Iterative imputer

In [199]:
def interative_imputer_run(df:pd.DataFrame):
    with mlflow.start_run():
            mlflow.set_tag("mlflow.runName", f"Interative Imputer Method")
            mlflow.set_tag("experiment_type", "fill null values")
            mlflow.log_param("mlflow.runName",f"Interative Imputer Method")
            df =df.dropna(how="any").reset_index(drop=True).copy()


            # build a preprocessor

            preprocessor = ColumnTransformer(transformers=[
                ("scale", MinMaxScaler(), num_cols),
                ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",sparse_output=False), nominal_cat_cols),
                ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order]), ordinal_cat_cols)
            ],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)

            preprocessor.set_output(transform="pandas")



            X = df.drop(columns='time_taken')
            y = df['time_taken']

            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

            # transform target column

            pt = PowerTransformer()
            pt.fit(y_train.values.reshape(-1,1))

            # model
            rf = RandomForestRegressor()

            model = TransformedTargetRegressor(
            regressor=rf,
            func=pt.transform,
            inverse_func=pt.inverse_transform
            )

            pipe = Pipeline(
            [

                ("preprocessor", preprocessor),
                ("interative imputer",IterativeImputer()),
                ("model", model),
            ]
            )

            cv_results = cross_validate(pipe,X_train,y_train,cv=5,return_train_score=True)

            # Extract test scores
            test_scores = cv_results["test_score"]

            mlflow.log_metric("cv_test_scores",np.mean(test_scores))
            mlflow.log_metric("cv_test_negative_std_scores",-1*np.std(test_scores))

            pipe.fit(X_train, y_train)

            mlflow.log_params(pipe.get_params())


            train_y_pred = pipe.predict(X_train)
            test_y_pred = pipe.predict(X_test)

            mlflow.log_metric("negative_train_MAE",-1*mean_absolute_error(y_train,train_y_pred))
            mlflow.log_metric("negative_test_MAE",-1*mean_absolute_error(y_test,test_y_pred))
            mlflow.log_metric("train_r2_score",r2_score(y_train,train_y_pred))
            mlflow.log_metric("test_r2_score",r2_score(y_test,test_y_pred))

In [200]:
interative_imputer_run(final_df)

🏃 View run Interative Imputer Method at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2/runs/939ac9a5c7414086a547184c707aaffd
🧪 View experiment at: https://spynom:@saurav2612@dagshub.com/spynom/my-first-repo.mlflow/#/experiments/2